apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: wildcard-delegation
  namespace: tap-install
spec:
  delegations:
  - secretName: wildcard
    targetNamespaces: ["*"]
