#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
profile: build
ceip_policy_disclosed: true

shared:
  image_registry:
    project_path: #@ "{}/{}".format(data.values.registry.fqdn, data.values.azure.acr.repository)
    username: #@ data.values.registry.username
    password: #@ data.values.registry.password
